name: apiverve_jsontojsonp
description: JSON to JSONP is a simple tool for converting JSON data into JSONP format. It returns the converted JSONP data.
version: 1.1.14
homepage: https://apiverve.com/marketplace/jsontojsonp?utm_source=dart&utm_medium=homepage
repository: https://github.com/apiverve/jsontojsonp-api/tree/main/dart

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  http: ^1.1.0
  http_parser: ^4.0.0

dev_dependencies:
  lints: ^3.0.0
  test: ^1.24.0
